version: '3.8'
services:
  api:
    build: .
    ports:
      - 8302:8302
    depends_on:
      - db
    container_name: monday-api
  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: monday-mongodb
